# Generated by Django 4.2.9 on 2024-01-18 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/EmployeeProfilePic/')),
                ('mode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('status', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
